In [4]:
import importlib.util
import subprocess
import sys

required = {
    "pandas": "pandas",
    "numpy": "numpy",
    "matplotlib": "matplotlib",
    "seaborn": "seaborn",
    "ipykernel": "ipykernel",
}

missing = [pkg for module, pkg in required.items() if importlib.util.find_spec(module) is None]

if missing:
    print(f"Instalando dependencias faltantes: {', '.join(missing)}")
    subprocess.check_call([sys.executable, "-m", "pip", "install", *missing])
else:
    print("Dependencias principais ja instaladas.")

Dependencias principais ja instaladas.

# Arquivo de Limpeza da Base

Nesse arquivo aqui, estamos apenas fazendo a junção dos diferentes CSV's vindos dos excels do limpe

# Importacao de Bibliotecas e Organização das Bases por Ano

**Importar as bibliotecas necessárias** para manipulação de dados (pandas), visualização (matplotlib, seaborn) e operações numéricas (numpy). Tambem inclui `re` para expressões regulares caso agnt precise usar (mas acho q n importa mto n).

In [5]:
import pandas as pd
import os 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re

**Carrega os dados de 2022** divididos em dois arquivos (janeiro-junho e julho-dezembro) e os concatena em um único dataframe.

**Visualizar as primeiras linhas de cada ano** para ter uma ideia da estrutura e conteúdo dos dados. As próximas 4 células mostram o preview de 2022, 2023, 2024 e 2025 respectivamente.

In [6]:
df_2022_jan = pd.read_csv("Bases/csv/2022_JAN_JUN.csv", sep=";", encoding="utf-8-sig")
df_2022_jul = pd.read_csv("Bases/csv/2022_JUL_DEZ.csv", sep=";", encoding="utf-8-sig")

df_2022 = pd.concat([df_2022_jan, df_2022_jul], ignore_index=True)

C:\Users\faldr\AppData\Local\Temp\ipykernel_22068\87640848.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2022_jan = pd.read_csv("Bases/csv/2022_JAN_JUN.csv", sep=";", encoding="utf-8-sig")

**Carrega os dados de 2023** (janeiro-junho e julho-dezembro) e os concatena.

In [7]:
df_2023_jan_jun = pd.read_csv("Bases/csv/2023_JAN_JUN.csv", sep=";", encoding="utf-8-sig")
df_2023_jul_dez = pd.read_csv("Bases/csv/2023_JUL_DEZ.csv", sep=";", encoding="utf-8-sig")

df_2023 = pd.concat([df_2023_jan_jun, df_2023_jul_dez], ignore_index=True)

C:\Users\faldr\AppData\Local\Temp\ipykernel_22068\1568925036.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023_jan_jun = pd.read_csv("Bases/csv/2023_JAN_JUN.csv", sep=";", encoding="utf-8-sig")

**Carrega os dados de 2024** (janeiro-junho e julho-dezembro) e os concatena.

In [8]:
df_2024_jan_jun = pd.read_csv("Bases/csv/2024_JAN_JUN.csv", sep=";", encoding="utf-8-sig")
df_2024_jul_dez = pd.read_csv("Bases/csv/2024_JUL_DEZ.csv", sep=";", encoding="utf-8-sig")

df_2024 = pd.concat([df_2024_jan_jun, df_2024_jul_dez], ignore_index=True)

C:\Users\faldr\AppData\Local\Temp\ipykernel_22068\2917193620.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024_jul_dez = pd.read_csv("Bases/csv/2024_JUL_DEZ.csv", sep=";", encoding="utf-8-sig")

**Carrega os dados de 2025** (janeiro-junho e julho-dezembro) e os concatena.

In [9]:
df_2025_jan_jun = pd.read_csv("Bases/csv/2025_JAN_JUN.csv", sep=";", encoding="utf-8-sig")
df_2025_jul_dez = pd.read_csv("Bases/csv/2025_JUL_DEZ.csv", sep=";", encoding="utf-8-sig")

df_2025 = pd.concat([df_2025_jan_jun, df_2025_jul_dez], ignore_index=True)

In [10]:
df_2022.head()

,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,CIDADE,NUM_BO,ANO_BO,DATA_COMUNICACAO_BO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESCR_PERIODO,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRIÇÃO,NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO,NOME_SECCIONAL_CIRCUNSCRIÇÃO,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
0,DECAP,DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022.0,13/01/2022,01/09/2021,NaN,EM HORA INCERTA,...,0,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1.0,2022.0
1,DECAP,DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022.0,03/01/2022,31/12/2021,15:20:00,NaN,...,"-46,6325199",01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1.0,2022.0
2,DECAP,DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022.0,04/01/2022,30/12/2021,NaN,EM HORA INCERTA,...,"-46,63109113",01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),TRANSEUNTE,FURTO - OUTROS,1.0,2022.0
3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022.0,03/01/2022,03/01/2022,16:00:00,NaN,...,"-46,6258725",01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1.0,2022.0
4,DECAP,DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022.0,03/01/2022,03/01/2022,13:30:00,NaN,...,"-46,63022391",01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),INTERIOR DE VEICULO,FURTO - OUTROS,1.0,2022.0

In [11]:
df_2023.head()

,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,...,LONGITUDE,NOME_DELEGACIA_CIRCUNSCRIÇÃO,NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO,NOME_SECCIONAL_CIRCUNSCRIÇÃO,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA
0,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AP5096,2023,14/01/2023,12/01/2023,21:00:19,NaN,...,0,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1,2023
1,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,BD2233,2023,25/01/2023,24/01/2023,20:40:00,NaN,...,0,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Art. 213 - Estupro,NaN,ESTUPRO,1,2023
2,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA0063,2023,31/12/2022,30/12/2022,NaN,A noite,...,NaN,01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2023
3,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA0404,2023,31/12/2022,30/12/2022,NaN,Pela manhã,...,"-46,632093172",01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2023
4,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA0895,2023,31/12/2022,30/12/2022,NaN,A tarde,...,"-46,626561700",01º D.P. SE,DECAP,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2023

In [12]:
df_2024.head()

,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,...,NOME_MUNICIPIO_CIRCUNSCRIÇÃO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA,CMD,BTL,CIA,COD IBGE
0,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AB8192,2024,02/01/2024,28/12/2023,23:55:00,NaN,...,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
1,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA0650,2024,01/01/2024,01/01/2024,NaN,De madrugada,...,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
2,DECAP,DEL.SEC.4º NORTE,13º D.P. CASA VERDE,S.PAULO,AA1075,2024,01/01/2024,31/12/2023,23:00:00,NaN,...,S.PAULO,Furto (art. 155),Transeunte,FURTO - OUTROS,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
3,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,AA1444,2024,01/01/2024,31/12/2023,23:00:00,NaN,...,S.PAULO,Furto (art. 155),Interior de Veículo,FURTO - OUTROS,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308
4,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,AA4651,2024,01/01/2024,31/12/2023,NaN,A tarde,...,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2024,CPA/M-1,7ºBPM/M,3ªCIA_4ªCIA,3550308

In [13]:
df_2025.head()

,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_REGISTRO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,...,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO,RUBRICA,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA,CMD,BTL,CIA
0,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AA2328,2025,01/01/2025,31/12/2024,18:00:00,NaN,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
1,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AM7136,2025,10/01/2025,10/01/2025,00:00:00,NaN,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
2,DECAP,DEL.SEC.1º CENTRO,01ª DDM CENTRO,S.PAULO,AQ9561,2025,14/01/2025,14/01/2025,NaN,Em hora incerta,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
3,DECAP,DEL.SEC.6º SANTO AMARO,06ª DDM SANTO AMARO,S.PAULO,BH3385,2025,27/01/2025,25/01/2025,18:00:14,NaN,...,DEL.SEC.1º CENTRO,S.PAULO,Estupro de vulneravel (art.217-A),NaN,ESTUPRO DE VULNERÁVEL,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA
4,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA 1,S.PAULO,AA1448,2025,01/01/2025,31/12/2024,10:30:00,NaN,...,DEL.SEC.1º CENTRO,S.PAULO,Furto (art. 155),Outros,FURTO - OUTROS,1,2025,CPA/M1,7ºBPM/M,3ªCIA 4ªCIA

Depois desses heads eu percebi que cada dupla de dataframe, ou seja (2022 - 2023) e (2024 - 2025) tinha um padrão especifico de variaveis, e ainda que entre si tinham diferenças sutis, entao era necessario renomear algumas coisas e tratar essas diferenças de acordo com o que é relevante, assim o que nao for importante e ter mais informacoes de uma para outra, nao precisa estar na final

(olhar o arquivo padronizar_colunas.py pq la ta mais explicadinho)

# Criando o DataFrame TOTAL

**Concatena todos os 4 anos em um único dataframe** para análise integrada dos dados de 2022 a 2025.

Ou seja, isso aqui é basicamente TODOS OS BO'S de todos os anos que temos na base do estado de SP (menos 2026 claro)

In [14]:
df_total = pd.concat([df_2022, df_2023, df_2024, df_2025], ignore_index=True)
#Ainda incluindo as colunas estranhas!

**Conta os registros por ano** para verificar a distribuição dos dados ao longo do período.

In [15]:
df_total["ANO_ESTATISTICA"].value_counts()

ANO_ESTATISTICA
2023.0    1241911
2022.0    1197973
2024.0    1191814
2025.0    1161132
Name: count, dtype: int64

**Visualizar o dataframe total consolidado** com todas as colunas e linhas dos 4 anos.

In [16]:
df_total
#31 colunas, pois juntamos as que tinham e nao tinha de todos os DF entre si, ou seja precisamos filtrar:

,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,CIDADE,NUM_BO,ANO_BO,DATA_COMUNICACAO_BO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESCR_PERIODO,...,DESC_PERIODO,DESCR_SUBTIPOLOCAL,CMD,BTL,CIA,COD IBGE,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_SECCIONAL_CIRCUNSCRICAO,NOME_MUNICIPIO_CIRCUNSCRICAO
0,DECAP,DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022.0,13/01/2022,01/09/2021,NaN,EM HORA INCERTA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DECAP,DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022.0,03/01/2022,31/12/2021,15:20:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DECAP,DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022.0,04/01/2022,30/12/2021,NaN,EM HORA INCERTA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022.0,03/01/2022,03/01/2022,16:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DECAP,DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022.0,03/01/2022,03/01/2022,13:30:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4792966,DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,NaN,SE6626,2025.0,NaN,12/12/2025,11:00:00,NaN,...,NaN,Casa,CPA/M-8,36ºBPM/M,2ªCIA,NaN,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
4792967,DEMACRO,DEL.SEC.TABOÃO DA SERRA,01º D.P. TABOÃO DA SERRA,NaN,SJ9736,2025.0,NaN,16/12/2025,11:20:00,NaN,...,NaN,Via Pública,CPA/M-8,36ºBPM/M,2ªCIA,NaN,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
4792968,DEMACRO,DEL.SEC.TABOÃO DA SERRA,DISE- DEL.SEC.TABOÃO SERRA,NaN,SK1616,2025.0,NaN,16/12/2025,NaN,NaN,...,A tarde,Via Pública,CPA/M-8,36ºBPM/M,2ªCIA,NaN,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
4792969,DEMACRO,DEL.SEC.TABOÃO DA SERRA,DISE- DEL.SEC.TABOÃO SERRA,NaN,SR6536,2025.0,NaN,22/12/2025,NaN,NaN,...,Pela manhã,Casa,CPA/M-8,36ºBPM/M,2ªCIA,NaN,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA
4792970,DEMACRO,DEL.SEC.TABOÃO DA SERRA,02º D.P. TABOÃO DA SERRA,NaN,SS1580,2025.0,NaN,22/12/2025,15:00:00,NaN,...,NaN,Via Pública,CPA/M-8,36ºBPM/M,2ªCIA,NaN,02º D.P. TABOÃO DA SERRA,DEMACRO,DEL.SEC.TABOÃO DA SERRA,TABOAO DA SERRA

# Ententendo o que precisa filtrar

**Análise detalhada das colunas por ano**: número de linhas e colunas em cada ano, listando todas as colunas. Ajuda a identificar inconsistências estruturais entre os períodos.

In [17]:
# Análise de Colunas: Comparação entre os anos
print("=" * 80)
print("COLUNAS POR ANO")
print("=" * 80)

years_data = {
    "2022": df_2022,
    "2023": df_2023,
    "2024": df_2024,
    "2025": df_2025
}

for year, df in years_data.items():
    print(f"\n{year}: {df.shape[0]} linhas, {df.shape[1]} colunas")
    print(f"Colunas: {sorted(df.columns.tolist())}")

#Pegando essencialmente todas as colunas, e vendo como elas diferem ao longo dos anos

================================================================================
COLUNAS POR ANO
================================================================================

2022: 1198114 linhas, 25 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'CIDADE', 'DATA_COMUNICACAO_BO', 'DATA_OCORRENCIA_BO', 'DESCR_CONDUTA', 'DESCR_PERIODO', 'DESCR_TIPOLOCAL', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

2023: 1241911 linhas, 25 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'DATA_OCORRENCIA_BO', 'DATA_REGISTRO', 'DESCR_CONDUTA', 'DESCR_SUBTIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

2024: 1191814 linhas, 29 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'BTL', 'CIA', 'CMD', 'COD IBGE', 'DATA_OCORRENCIA_BO', 'DATA_REGISTRO', 'DESCR_CONDUTA', 'DESCR_SUBTIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

2025: 1161132 linhas, 29 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'BTL', 'CIA', 'CMD', 'DATA_OCORRENCIA_BO', 'DATA_REGISTRO', 'DESCR_CONDUTA', 'DESCR_SUBTIPOLOCAL', 'DESCR_TIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

Bem perceptível que os asno 2024 e 2025 tem as mesmas colunas, porem ainda assim com os nomes nao padronizados, enquanto os anos 2023 e 2022 tem essa semelhanca entre si

(Apesar de que na verdade tem algumas informacoes que uma ou outra nao tem)

Agora precisamos **Encontrar colunas que são iguais em todos os anos e colunas que diferem**. Mostra quais colunas estão faltando em cada período, ajudando a identificar o que precisa ser padronizado.

**Apresenta as duas opções de dataset final**: a versão com todas as colunas (df_total) e a versão limpa apenas com colunas completas (df_total_completo) recomendada para análises.

**Salva a documentação completa em um arquivo Markdown** (DOCUMENTACAO_COLUNAS.md) com todas as informações de mapeamento e análise de colunas para referência futura.

In [18]:
# Encontrar colunas comuns e diferences
print("\n" + "=" * 80)
print("ANÁLISE DE DIFERENÇAS NAS COLUNAS")
print("=" * 80)

all_columns = {year: set(df.columns) for year, df in years_data.items()}

# Colunas comuns em todos os anos
common_columns = set.intersection(*all_columns.values())
print(f"\n Colunas presentes em TODOS os anos ({len(common_columns)} colunas):")
print(sorted(common_columns))

# Colunas por ano que podem estar faltando em outras
print("\n\n" + "-" * 80)
print("COLUNAS ESPECÍFICAS POR ANO (não presentes em todos):")
print("-" * 80)

for year in ["2022", "2023", "2024", "2025"]:
    unique_to_year = all_columns[year] - common_columns
    if unique_to_year:
        print(f"\n{year}: {unique_to_year}")
    else:
        print(f"\n{year}: Nenhuma coluna única")

# Colunas faltando por ano
print("\n\n" + "-" * 80)
print("COLUNAS FALTANDO EM CADA ANO:")
print("-" * 80)

for year in ["2022", "2023", "2024", "2025"]:
    missing = set()
    for other_year in ["2022", "2023", "2024", "2025"]:
        if year != other_year:
            missing.update(all_columns[other_year] - all_columns[year])
    
    if missing:
        print(f"\n{year} (faltam {len(missing)} colunas):")
        for col in sorted(missing):
            print(f"  - {col}")

================================================================================
ANÁLISE DE DIFERENÇAS NAS COLUNAS
================================================================================

 Colunas presentes em TODOS os anos (17 colunas):
['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'DATA_OCORRENCIA_BO', 'DESCR_CONDUTA', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DEPARTAMENTO', 'NOME_SECCIONAL', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']


--------------------------------------------------------------------------------
COLUNAS ESPECÍFICAS POR ANO (não presentes em todos):
--------------------------------------------------------------------------------

2022: {'DATA_COMUNICACAO_BO', 'CIDADE', 'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'DESCR_TIPOLOCAL', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 'DESCR_PERIODO'}

2023: {'DESCR_SUBTIPOLOCAL', 'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'DATA_REGISTRO', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 'DESC_PERIODO'}

2024: {'DESCR_SUBTIPOLOCAL', 'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'DATA_REGISTRO', 'COD IBGE', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO', 'CMD', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO', 'BTL', 'CIA', 'DESC_PERIODO'}

2025: {'DESCR_SUBTIPOLOCAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'DATA_REGISTRO', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'DESCR_TIPOLOCAL', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'CMD', 'BTL', 'CIA', 'DESC_PERIODO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO'}


--------------------------------------------------------------------------------
COLUNAS FALTANDO EM CADA ANO:
--------------------------------------------------------------------------------

2022 (faltam 12 colunas):
  - BTL
  - CIA
  - CMD
  - COD IBGE
  - DATA_REGISTRO
  - DESCR_SUBTIPOLOCAL
  - DESC_PERIODO
  - NOME_DELEGACIA_CIRCUNSCRICAO
  - NOME_DEPARTAMENTO_CIRCUNSCRICAO
  - NOME_MUNICIPIO
  - NOME_MUNICIPIO_CIRCUNSCRICAO
  - NOME_SECCIONAL_CIRCUNSCRICAO

2023 (faltam 12 colunas):
  - BTL
  - CIA
  - CIDADE
  - CMD
  - COD IBGE
  - DATA_COMUNICACAO_BO
  - DESCR_PERIODO
  - DESCR_TIPOLOCAL
  - NOME_DELEGACIA_CIRCUNSCRICAO
  - NOME_DEPARTAMENTO_CIRCUNSCRICAO
  - NOME_MUNICIPIO_CIRCUNSCRICAO
  - NOME_SECCIONAL_CIRCUNSCRICAO

2024 (faltam 8 colunas):
  - CIDADE
  - DATA_COMUNICACAO_BO
  - DESCR_PERIODO
  - DESCR_TIPOLOCAL
  - NOME_DELEGACIA_CIRCUNSCRICAO
  - NOME_DEPARTAMENTO_CIRCUNSCRICAO
  - NOME_MUNICIPIO_CIRCUNSCRICAO
  - NOME_SECCIONAL_CIRCUNSCRICAO

2025 (faltam 8 colunas):
  - CIDADE
  - COD IBGE
  - DATA_COMUNICACAO_BO
  - DESCR_PERIODO
  - NOME_DELEGACIA_CIRCUNSCRIÇÃO
  - NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO
  - NOME_MUNICIPIO_CIRCUNSCRIÇÃO
  - NOME_SECCIONAL_CIRCUNSCRIÇÃO

**Identifica as relações entre colunas que têm a mesma função mas nomes diferentes** (por exemplo, "CIDADE" vs "NOME_MUNICIPIO"). Também encontra colunas completamente novas em 2024-2025.

In [19]:
# Mapeamento de Colunas Equivalentes (mesma função, nomes diferentes)
print("\n" + "=" * 80)
print("MAPEAMENTO DE COLUNAS COM MESMA FUNÇÃO (nomes diferentes)")
print("=" * 80)

column_mapping = {
    "PERÍODO": ["DESCR_PERIODO", "DESC_PERIODO"],
    "TIPO LOCAL": ["DESCR_TIPOLOCAL", "DESCR_SUBTIPOLOCAL"],
    "MUNICÍPIO": ["CIDADE", "NOME_MUNICIPIO"],
    "CIRCUNSCRIÇÃO (acentuação)": ["NOME_DELEGACIA_CIRCUNSCRIÇÃO", "NOME_DELEGACIA_CIRCUNSCRICAO"],
}

for func, variants in column_mapping.items():
    print(f"\n{func}:")
    for col in variants:
        years_with_col = [year for year, cols in all_columns.items() if col in cols]
        print(f"  {col:40} → {', '.join(years_with_col)}")

# Colunas novass (2024+)
print("\n" + "=" * 80)
print("COLUNAS NOVAS EM 2024-2025 (não em 2022-2023):")
print("=" * 80)
new_cols_2024 = all_columns["2024"] - (all_columns["2022"] | all_columns["2023"])
print(f"\nNovas em 2024: {new_cols_2024}")

# Comparar 2024 vs 2025
print("\n" + "-" * 80)
print("Diferença entre 2024 e 2025:")
print("-" * 80)
only_2024 = all_columns["2024"] - all_columns["2025"]
only_2025 = all_columns["2025"] - all_columns["2024"]
print(f"Apenas em 2024: {only_2024}")
print(f"Apenas em 2025: {only_2025}")

================================================================================
MAPEAMENTO DE COLUNAS COM MESMA FUNÇÃO (nomes diferentes)
================================================================================

PERÍODO:
  DESCR_PERIODO                            → 2022
  DESC_PERIODO                             → 2023, 2024, 2025

TIPO LOCAL:
  DESCR_TIPOLOCAL                          → 2022, 2025
  DESCR_SUBTIPOLOCAL                       → 2023, 2024, 2025

MUNICÍPIO:
  CIDADE                                   → 2022
  NOME_MUNICIPIO                           → 2023, 2024, 2025

CIRCUNSCRIÇÃO (acentuação):
  NOME_DELEGACIA_CIRCUNSCRIÇÃO             → 2022, 2023, 2024
  NOME_DELEGACIA_CIRCUNSCRICAO             → 2025

================================================================================
COLUNAS NOVAS EM 2024-2025 (não em 2022-2023):
================================================================================

Novas em 2024: {'CIA', 'COD IBGE', 'CMD', 'BTL'}

--------------------------------------------------------------------------------
Diferença entre 2024 e 2025:
--------------------------------------------------------------------------------
Apenas em 2024: {'NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO', 'COD IBGE', 'NOME_SECCIONAL_CIRCUNSCRIÇÃO', 'NOME_MUNICIPIO_CIRCUNSCRIÇÃO', 'NOME_DELEGACIA_CIRCUNSCRIÇÃO'}
Apenas em 2025: {'NOME_SECCIONAL_CIRCUNSCRICAO', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'DESCR_TIPOLOCAL', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO'}

**Aplica a padronização de nomes de colunas** usando o mapeamento identificado, renomeando colunas equivalentes para nomes consistentes em todos os anos. Depois reconstrói o dataframe total com os nomes padronizados.

In [20]:
# SOLUÇÃO: Padronizar nomes de colunas e filtrar apenas colunas completas

# 1. Definir mapeamento completo de renomeação
rename_mapping = {
    # Período
    "DESCR_PERIODO": "DESC_PERIODO",
    
    # Tipo de Local (2025 trouxe de volta DESCR_TIPOLOCAL)
    # Vamos manter DESCR_SUBTIPOLOCAL como padrão
    
    # Município
    "CIDADE": "NOME_MUNICIPIO",
    
    # Acentuação (remover circunflexo para padronizar)
    "NOME_DELEGACIA_CIRCUNSCRIÇÃO": "NOME_DELEGACIA_CIRCUNSCRICAO",
    "NOME_DEPARTAMENTO_CIRCUNSCRIÇÃO": "NOME_DEPARTAMENTO_CIRCUNSCRICAO",
    "NOME_MUNICIPIO_CIRCUNSCRIÇÃO": "NOME_MUNICIPIO_CIRCUNSCRICAO",
    "NOME_SECCIONAL_CIRCUNSCRIÇÃO": "NOME_SECCIONAL_CIRCUNSCRICAO",
}

# 2. Aplicar renomeação em cada dataframe
for year in ["2022", "2023", "2024", "2025"]:
    years_data[year] = years_data[year].rename(columns=rename_mapping)

# 3. Recriar df_total com colunas renomeadas
df_total = pd.concat([years_data[year] for year in ["2022", "2023", "2024", "2025"]], ignore_index=True)

print("=" * 80)
print("COLUNAS APÓS PADRONIZAÇÃO")
print("=" * 80)

for year in ["2022", "2023", "2024", "2025"]:
    print(f"\n{year}: {len(years_data[year].columns)} colunas")
    print(f"Colunas: {sorted(years_data[year].columns.tolist())}")

================================================================================
COLUNAS APÓS PADRONIZAÇÃO
================================================================================

2022: 25 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'DATA_COMUNICACAO_BO', 'DATA_OCORRENCIA_BO', 'DESCR_CONDUTA', 'DESCR_TIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

2023: 25 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'DATA_OCORRENCIA_BO', 'DATA_REGISTRO', 'DESCR_CONDUTA', 'DESCR_SUBTIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

2024: 29 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'BTL', 'CIA', 'CMD', 'COD IBGE', 'DATA_OCORRENCIA_BO', 'DATA_REGISTRO', 'DESCR_CONDUTA', 'DESCR_SUBTIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

2025: 29 colunas
Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'BTL', 'CIA', 'CMD', 'DATA_OCORRENCIA_BO', 'DATA_REGISTRO', 'DESCR_CONDUTA', 'DESCR_SUBTIPOLOCAL', 'DESCR_TIPOLOCAL', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

**Identifica colunas "completas" (presentes em todos os 4 anos) vs "incompletas"** (que faltam em algum período). Cria um dataframe filtrado com apenas as colunas completas para análises sem valores faltantes (NaN).

In [21]:
# Identificar colunas COMPLETAS (presentes em todos os 4 anos)
print("\n" + "=" * 80)
print("ANÁLISE FINAL: COLUNAS COMPLETAS vs INCOMPLETAS")
print("=" * 80)

# Atualizar sets de colunas
all_columns_after = {year: set(years_data[year].columns) for year in ["2022", "2023", "2024", "2025"]}

# Colunas comuns em todos
complete_columns = set.intersection(*all_columns_after.values())
print(f"\n✓ COLUNAS COMPLETAS (presentes em todos 4 anos): {len(complete_columns)}")
print(sorted(complete_columns))

# Colunas incompletas
incomplete_columns = set.union(*all_columns_after.values()) - complete_columns
print(f"\n✗ COLUNAS INCOMPLETAS (faltam em algum ano): {len(incomplete_columns)}")

for col in sorted(incomplete_columns):
    years_present = [year for year in ["2022", "2023", "2024", "2025"] if col in all_columns_after[year]]
    years_missing = [year for year in ["2022", "2023", "2024", "2025"] if col not in all_columns_after[year]]
    print(f"  {col:45} → Tem: {years_present}, Falta em: {years_missing}")

# Criar df_total_completo com apenas colunas completas
df_total_completo = df_total[sorted(complete_columns)]

print("\n" + "=" * 80)
print("RESULTADO FINAL")
print("=" * 80)
print(f"\ndf_total (com todas as colunas):")
print(f"  - Linhas: {df_total.shape[0]}")
print(f"  - Colunas: {df_total.shape[1]}")

print(f"\ndf_total_completo (apenas colunas presentes em todos os anos):")
print(f"  - Linhas: {df_total_completo.shape[0]}")
print(f"  - Colunas: {df_total_completo.shape[1]}")
print(f"  - Colunas: {sorted(df_total_completo.columns.tolist())}")

================================================================================
ANÁLISE FINAL: COLUNAS COMPLETAS vs INCOMPLETAS
================================================================================

✓ COLUNAS COMPLETAS (presentes em todos 4 anos): 23
['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'DATA_OCORRENCIA_BO', 'DESCR_CONDUTA', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

✗ COLUNAS INCOMPLETAS (faltam em algum ano): 8
  BTL                                           → Tem: ['2024', '2025'], Falta em: ['2022', '2023']
  CIA                                           → Tem: ['2024', '2025'], Falta em: ['2022', '2023']
  CMD                                           → Tem: ['2024', '2025'], Falta em: ['2022', '2023']
  COD IBGE                                      → Tem: ['2024'], Falta em: ['2022', '2023', '2025']
  DATA_COMUNICACAO_BO                           → Tem: ['2022'], Falta em: ['2023', '2024', '2025']
  DATA_REGISTRO                                 → Tem: ['2023', '2024', '2025'], Falta em: ['2022']
  DESCR_SUBTIPOLOCAL                            → Tem: ['2023', '2024', '2025'], Falta em: ['2022']
  DESCR_TIPOLOCAL                               → Tem: ['2022', '2025'], Falta em: ['2023', '2024']

================================================================================
RESULTADO FINAL
================================================================================

df_total (com todas as colunas):
  - Linhas: 4792971
  - Colunas: 31

df_total_completo (apenas colunas presentes em todos os anos):
  - Linhas: 4792971
  - Colunas: 23
  - Colunas: ['ANO_BO', 'ANO_ESTATISTICA', 'BAIRRO', 'DATA_OCORRENCIA_BO', 'DESCR_CONDUTA', 'DESC_PERIODO', 'HORA_OCORRENCIA_BO', 'LATITUDE', 'LOGRADOURO', 'LONGITUDE', 'MES_ESTATISTICA', 'NATUREZA_APURADA', 'NOME_DELEGACIA', 'NOME_DELEGACIA_CIRCUNSCRICAO', 'NOME_DEPARTAMENTO', 'NOME_DEPARTAMENTO_CIRCUNSCRICAO', 'NOME_MUNICIPIO', 'NOME_MUNICIPIO_CIRCUNSCRICAO', 'NOME_SECCIONAL', 'NOME_SECCIONAL_CIRCUNSCRICAO', 'NUMERO_LOGRADOURO', 'NUM_BO', 'RUBRICA']

In [22]:
# Comparação antes/depois e duas opções de dataset final
print("\n" + "=" * 80)
print("DUAS OPCOES PARA O DATASET FINAL")
print("=" * 80)

print(f"\n📊 OPTION 1: DATA FRAME TOTAL (COM NOMES PADROES DE COLUNAS)")
print(f"   Colunas: {df_total.shape[1]}")
print(f"   Linhas: {df_total.shape[0]:,}")
print(f"   ⚠️  Contém valores NaN onde colunas faltam:")
for col in sorted(incomplete_columns):
    null_count = df_total[col].isna().sum() if col in df_total.columns else 0
    print(f"      - {col:40} → {null_count:,} NaN values")

print(f"\n📊 OPCAO 2: df_total_completo (only complete columns)")
print(f"   Colunas: {df_total_completo.shape[1]}")
print(f"   Linhas: {df_total_completo.shape[0]:,}")
print(f"   ✓ SEM valores NaN (dados 100% completos)")
print(f"   ✓ {len(complete_columns)} colunas consistentes em todos os anos")

print("\n" + "-" * 80)
print("RECOMENDAÇÃO:")
print("-" * 80)
print("Use 'df_total_completo' para análises mais limpas e consistentes!")
print("Todas as colunas têm dados em todos os 4 anos de períodos.")

# Preview dos dados
print("\n" + "=" * 80)
print("PREVIEW: df_total_completo.head()")
print("=" * 80)
print(df_total_completo.head())

================================================================================
DUAS OPCOES PARA O DATASET FINAL
================================================================================

📊 OPTION 1: DATA FRAME TOTAL (COM NOMES PADROES DE COLUNAS)
   Colunas: 31
   Linhas: 4,792,971
   ⚠️  Contém valores NaN onde colunas faltam:
      - BTL                                      → 2,440,025 NaN values
      - CIA                                      → 2,440,025 NaN values
      - CMD                                      → 2,440,025 NaN values
      - COD IBGE                                 → 3,601,157 NaN values
      - DATA_COMUNICACAO_BO                      → 3,598,179 NaN values
      - DATA_REGISTRO                            → 1,198,115 NaN values
      - DESCR_SUBTIPOLOCAL                       → 1,218,841 NaN values
      - DESCR_TIPOLOCAL                          → 2,434,547 NaN values

📊 OPCAO 2: df_total_completo (only complete columns)
   Colunas: 23
   Linhas: 4,792,971
   ✓ SEM valores NaN (dados 100% completos)
   ✓ 23 colunas consistentes em todos os anos

--------------------------------------------------------------------------------
RECOMENDAÇÃO:
--------------------------------------------------------------------------------
Use 'df_total_completo' para análises mais limpas e consistentes!
Todas as colunas têm dados em todos os 4 anos de períodos.

================================================================================
PREVIEW: df_total_completo.head()
================================================================================
   ANO_BO  ANO_ESTATISTICA                         BAIRRO DATA_OCORRENCIA_BO  \
0  2022.0           2022.0                             SE         01/09/2021
1  2022.0           2022.0  Centro Histórico de São Paulo         31/12/2021
2  2022.0           2022.0                             SE         30/12/2021
3  2022.0           2022.0                      Liberdade         03/01/2022
4  2022.0           2022.0                      LIBERDADE         03/01/2022

         DESCR_CONDUTA     DESC_PERIODO HORA_OCORRENCIA_BO      LATITUDE  \
0                  NaN  EM HORA INCERTA                NaN             0
1  INTERIOR DE VEICULO              NaN           15:20:00   -23,5436238
2           TRANSEUNTE  EM HORA INCERTA                NaN  -23,54502538
3  INTERIOR DE VEICULO              NaN           16:00:00   -23,5535658
4  INTERIOR DE VEICULO              NaN           13:30:00  -23,55805038

                                  LOGRADOURO     LONGITUDE  ...  \
0  VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS             0  ...
1                                25 de Março   -46,6325199  ...
2                        PARQUE DOM PEDRO II  -46,63109113  ...
3                 Viaduto Therezinha Zerbini   -46,6258725  ...
4                            RUA DO GLICERIO  -46,63022391  ...

   NOME_DELEGACIA_CIRCUNSCRICAO NOME_DEPARTAMENTO  \
0                   01º D.P. SE             DECAP
1                   01º D.P. SE             DECAP
2                   01º D.P. SE             DECAP
3                   01º D.P. SE             DECAP
4                   01º D.P. SE             DECAP

  NOME_DEPARTAMENTO_CIRCUNSCRICAO NOME_MUNICIPIO NOME_MUNICIPIO_CIRCUNSCRICAO  \
0                           DECAP        S.PAULO                      S.PAULO
1                           DECAP        S.PAULO                      S.PAULO
2                           DECAP        S.PAULO                      S.PAULO
3                           DECAP        S.PAULO                      S.PAULO
4                           DECAP        S.PAULO                      S.PAULO

          NOME_SECCIONAL NOME_SECCIONAL_CIRCUNSCRICAO NUMERO_LOGRADOURO  \
0  DEL.SEC.8º SAO MATEUS            DEL.SEC.1º CENTRO               NaN
1  DEL.SEC.8º SAO MATEUS            DEL.SEC.1º CENTRO               325
2       DEL.SEC.5º LESTE            DEL.SEC.1º CENTRO                10
3      DEL.SEC.1º CENTRO            DEL.SEC.1º CENTRO                 1
4      DEL.SEC.1º CENTRO            DEL.SEC.1º CENTRO               NaN

   NUM_BO             RUBRICA
0  AC0851  Art. 213 - Estupro
1       4    Furto (art. 155)
2       7    Furto (art. 155)
3       8    Furto (art. 155)
4       8    Furto (art. 155)

[5 rows x 23 columns]

### O resumo de tudo o que foi feito está la no DOCUMENTACAO.md

**Visualiza as primeiras linhas do df_total** (com todas as colunas e dados padronizados).

In [23]:
df_total.head()

,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,NUM_BO,ANO_BO,DATA_COMUNICACAO_BO,DATA_OCORRENCIA_BO,HORA_OCORRENCIA_BO,DESC_PERIODO,...,DESCR_CONDUTA,NATUREZA_APURADA,MES_ESTATISTICA,ANO_ESTATISTICA,DATA_REGISTRO,DESCR_SUBTIPOLOCAL,CMD,BTL,CIA,COD IBGE
0,DECAP,DEL.SEC.8º SAO MATEUS,08ª DDM SAO MATEUS,S.PAULO,AC0851,2022.0,13/01/2022,01/09/2021,NaN,EM HORA INCERTA,...,NaN,ESTUPRO,1.0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN
1,DECAP,DEL.SEC.8º SAO MATEUS,54º D.P. CID. TIRADENTES,S.PAULO,4,2022.0,03/01/2022,31/12/2021,15:20:00,NaN,...,INTERIOR DE VEICULO,FURTO - OUTROS,1.0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN
2,DECAP,DEL.SEC.5º LESTE,29º D.P. VILA PRUDENTE,S.PAULO,7,2022.0,04/01/2022,30/12/2021,NaN,EM HORA INCERTA,...,TRANSEUNTE,FURTO - OUTROS,1.0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN
3,DECAP,DEL.SEC.1º CENTRO,01º D.P. SE,S.PAULO,8,2022.0,03/01/2022,03/01/2022,16:00:00,NaN,...,INTERIOR DE VEICULO,FURTO - OUTROS,1.0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN
4,DECAP,DEL.SEC.1º CENTRO,06º D.P. CAMBUCI,S.PAULO,8,2022.0,03/01/2022,03/01/2022,13:30:00,NaN,...,INTERIOR DE VEICULO,FURTO - OUTROS,1.0,2022.0,NaN,NaN,NaN,NaN,NaN,NaN

**Verifica como "São Paulo" está registrado nos dados** -  lista todas as cidades com mais feminicídios para identificar a variação no nome (S.PAULO, PAULO, SÃO PAULO, etc).

**Visualiza as primeiras linhas do df_total_completo** (apenas colunas presentes em todos os anos, sem NaN).

In [24]:
df_total_completo.head()

,ANO_BO,ANO_ESTATISTICA,BAIRRO,DATA_OCORRENCIA_BO,DESCR_CONDUTA,DESC_PERIODO,HORA_OCORRENCIA_BO,LATITUDE,LOGRADOURO,LONGITUDE,...,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_MUNICIPIO,NOME_MUNICIPIO_CIRCUNSCRICAO,NOME_SECCIONAL,NOME_SECCIONAL_CIRCUNSCRICAO,NUMERO_LOGRADOURO,NUM_BO,RUBRICA
0,2022.0,2022.0,SE,01/09/2021,NaN,EM HORA INCERTA,NaN,0,VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,0,...,01º D.P. SE,DECAP,DECAP,S.PAULO,S.PAULO,DEL.SEC.8º SAO MATEUS,DEL.SEC.1º CENTRO,NaN,AC0851,Art. 213 - Estupro
1,2022.0,2022.0,Centro Histórico de São Paulo,31/12/2021,INTERIOR DE VEICULO,NaN,15:20:00,"-23,5436238",25 de Março,"-46,6325199",...,01º D.P. SE,DECAP,DECAP,S.PAULO,S.PAULO,DEL.SEC.8º SAO MATEUS,DEL.SEC.1º CENTRO,325,4,Furto (art. 155)
2,2022.0,2022.0,SE,30/12/2021,TRANSEUNTE,EM HORA INCERTA,NaN,"-23,54502538",PARQUE DOM PEDRO II,"-46,63109113",...,01º D.P. SE,DECAP,DECAP,S.PAULO,S.PAULO,DEL.SEC.5º LESTE,DEL.SEC.1º CENTRO,10,7,Furto (art. 155)
3,2022.0,2022.0,Liberdade,03/01/2022,INTERIOR DE VEICULO,NaN,16:00:00,"-23,5535658",Viaduto Therezinha Zerbini,"-46,6258725",...,01º D.P. SE,DECAP,DECAP,S.PAULO,S.PAULO,DEL.SEC.1º CENTRO,DEL.SEC.1º CENTRO,1,8,Furto (art. 155)
4,2022.0,2022.0,LIBERDADE,03/01/2022,INTERIOR DE VEICULO,NaN,13:30:00,"-23,55805038",RUA DO GLICERIO,"-46,63022391",...,01º D.P. SE,DECAP,DECAP,S.PAULO,S.PAULO,DEL.SEC.1º CENTRO,DEL.SEC.1º CENTRO,NaN,8,Furto (art. 155)

**Visualiza os primeiros registros de feminicídios** para entender melhor os dados e as informações disponíveis em cada caso.

In [25]:
df_total_completo[df_total_completo["DESCR_CONDUTA"] == "Feminicídio-contra a mulher por razões da condição de sexo feminino."].shape[0]

1636

**Armazena a contagem de feminicídios em uma variável** para uso posterior e exibe o resultado.

In [26]:
contagem_de_feminicidios = df_total_completo[df_total_completo["DESCR_CONDUTA"] == "Feminicídio-contra a mulher por razões da condição de sexo feminino."].shape[0]
print(f"Total de feminicídios: {contagem_de_feminicidios}")

Total de feminicídios: 1636

**Conta o total de ocorrências criminais** no periodo completo (2022-2025) para contexto das análises.

In [27]:
total_de_BO = df_total_completo.shape[0]
print(f"Total de ocorrências criminais (2022-2025): {total_de_BO:,}")

Total de ocorrências criminais (2022-2025): 4,792,971

**Análise específica: feminicídios em São Paulo** (2022-2025). Filtra por DESCR_CONDUTA e NOME_MUNICIPIO.

In [28]:
# Feminicídios em São Paulo
feminicidios_sp = df_total_completo[
    (df_total_completo["DESCR_CONDUTA"] == "Feminicídio-contra a mulher por razões da condição de sexo feminino.") &
    (df_total_completo["NOME_MUNICIPIO"] == "S.PAULO")
].shape[0]

print(f"Feminicídios em São Paulo (2022-2025): {feminicidios_sp:,}")
print(f"Percentual do total: {(feminicidios_sp / 1636) * 100:.1f}%")

Feminicídios em São Paulo (2022-2025): 371
Percentual do total: 22.7%

**COMEÇANDO a análise: contar todos os feminicídios** registrados no dataset (de 2022 a 2025). Filtra apenas registros onde DESCR_CONDUTA é "Feminicídio".

In [29]:
# Verificar como "São Paulo" está registrado
feminicidios_df = df_total_completo[
    df_total_completo["DESCR_CONDUTA"] == "Feminicídio-contra a mulher por razões da condição de sexo feminino."
]

print("Cidades com mais feminicídios:")
print(feminicidios_df["NOME_MUNICIPIO"].value_counts().head(600))

Cidades com mais feminicídios:
NOME_MUNICIPIO
S.PAULO                371
GUARULHOS               41
CAMPINAS                36
S.JOSE DO RIO PRETO     30
OSASCO                  26
                      ...
PIRAPORA BOM JESUS       1
POA                      1
PARAPUA                  1
DOLCINOPOLIS             1
S.MARIA DA SERRA         1
Name: count, Length: 334, dtype: int64

In [30]:
feminicidios_df.head()

,ANO_BO,ANO_ESTATISTICA,BAIRRO,DATA_OCORRENCIA_BO,DESCR_CONDUTA,DESC_PERIODO,HORA_OCORRENCIA_BO,LATITUDE,LOGRADOURO,LONGITUDE,...,NOME_DELEGACIA_CIRCUNSCRICAO,NOME_DEPARTAMENTO,NOME_DEPARTAMENTO_CIRCUNSCRICAO,NOME_MUNICIPIO,NOME_MUNICIPIO_CIRCUNSCRICAO,NOME_SECCIONAL,NOME_SECCIONAL_CIRCUNSCRICAO,NUMERO_LOGRADOURO,NUM_BO,RUBRICA
26207,2022.0,2022.0,PARQUE FERNANDA,22/01/2022,Feminicídio-contra a mulher por razões da cond...,NaN,20:00:00,0,VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,0,...,47º D.P. CAPAO REDONDO,DECAP,DECAP,S.PAULO,S.PAULO,DEL.SEC.6º SANTO AMARO,DEL.SEC.6º SANTO AMARO,NaN,AE2379,Homicídio (art. 121)
40911,2022.0,2022.0,BELVEDERE,12/01/2022,Feminicídio-contra a mulher por razões da cond...,NaN,20:10:00,0,VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,0,...,DEL.POL.PENÁPOLIS,DEINTER 10 - ARAÇATUBA,DEINTER 10 - ARAÇATUBA,PENAPOLIS,PENAPOLIS,DEL.SEC.ARACATUBA,DEL.SEC.ARACATUBA,NaN,AC0317,Homicídio (art. 121)
63082,2022.0,2022.0,AREA RURAL,12/01/2022,Feminicídio-contra a mulher por razões da cond...,NaN,19:00:00,0,VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,0,...,01º D.P. GUARUJA,DEINTER 6 - SANTOS,DEINTER 6 - SANTOS,GUARUJA,GUARUJA,DEL.SEC.SANTOS,DEL.SEC.SANTOS,NaN,AC4630,Homicídio (art. 121)
75414,2022.0,2022.0,PARQUE IMPERIAL,09/01/2022,Feminicídio-contra a mulher por razões da cond...,NaN,21:00:00,0,VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,0,...,02º D.P. BARUERI,DEMACRO,DEMACRO,BARUERI,BARUERI,DEL.SEC.CARAPICUIBA,DEL.SEC.CARAPICUIBA,NaN,AB3503,Homicídio (art. 121)
75605,2022.0,2022.0,JD ESPERANÇA,24/01/2022,Feminicídio-contra a mulher por razões da cond...,EM HORA INCERTA,NaN,0,VEDAÇÃO DA DIVULGAÇÃO DOS DADOS RELATIVOS,0,...,DEL.POL.BARUERI,DEMACRO,DEMACRO,BARUERI,BARUERI,DEL.SEC.CARAPICUIBA,DEL.SEC.CARAPICUIBA,NaN,AF1638,Homicídio (art. 121)

In [31]:
output_path = "Bases/csv/feminicidios_2022_2025.csv"
feminicidios_df.to_csv(output_path, index=False, encoding="utf-8-sig")
print(f"CSV salvo em: {output_path}")
print(f"Total de linhas: {len(feminicidios_df):,}")

CSV salvo em: Bases/csv/feminicidios_2022_2025.csv
Total de linhas: 1,636